planemodel_index:
    path:     /
    defaults: { _controller: "WVScoavBundle:PlaneModel:index" }
    methods:  GET

planemodel_show:
    path:     /{id}/show
    defaults: { _controller: "WVScoavBundle:PlaneModel:show" }
    methods:  GET

planemodel_new:
    path:     /new
    defaults: { _controller: "WVScoavBundle:PlaneModel:new" }
    methods:  [GET, POST]

planemodel_edit:
    path:     /{id}/edit
    defaults: { _controller: "WVScoavBundle:PlaneModel:edit" }
    methods:  [GET, POST]

planemodel_delete:
    path:     /{id}/delete
    defaults: { _controller: "WVScoavBundle:PlaneModel:delete" }
    methods:  DELETE
