WVS\coavBundle\Entity\Flight:
    type: entity
    table: null
    repositoryClass: WVS\coavBundle\Repository\FlightRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        arrival:
            type: string
            length: '4'
        pilote:
            type: string
            length: 255
        freeSeats:
            type: integer
            nullable: true
        takeofTime:
            type: datetime
    lifecycleCallbacks: {  }

    manyToOne:
        departure:
            targetEntity: WVS\coavBundle\Entity\Terrain
            inversedBy: departures
